### ISSUE TITLE
Allocation of Tasks

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#18]
- Executive Summary (Houston)
- Problem Definition: Objectives, List of Stakeholders (Everyone... however, Alisa will finalise)
- Design Thinking Approach to Address the Problem with Artefacts (Jordan)
- Workproducts, Models and Descriptions (Everyone)
- Competitive Advantages and Possible Effects if the Project Fails (Karina)
- Using GitHub to Role-play Agile Methodologies (Everyone)

Is everyone okay with this? Any suggestions or problems?
Keep in mind everyone will be helping each other and editing all sections (regardless of "assigned" part") by constantly communicating in order to ensure consistency and accuracy of our finalised project.

**Comment by Leng-Houston** [comment]
Ok no problem

**Comment by alisalam5** [comment]
Sounds good. Collaboration is key.

**Comment by Kin-Shun-Jordan-Wong** [comment]
Alright perfect, thanks Karina.
