### ISSUE TITLE
user stories for product backlog 

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#20]
• As a customer, I want to be personally matched to an appropriate RM based on their performance and product knowledge so that I will be able to obtain the highest-quality and most enjoyable travel experience.
• As an RM, I want to build a profile and skill matrix through an initial questionnaire so that I will be able to better satisfy and serve customers more effectively and efficiently.
• As a customer, I want to have a quick response when calling up the travel company so that I can be served effectively and efficiently.
• As an RM, I want to serve customers with the highest purchase likelihood score first so that the chance of achieving a sale will increase.
• As a customer, I want to be redirected to the first available appropriate RM during busy times so that I can be served effectively and efficiently.
•	As a customer, I want to be provided a service that is knowledgeable towards my social and cultural needs so that I may find a suitable holiday packet.
•	As an RM, I want to be provided with an assisting tool (target list) so that I can improve my sales and service for new potential customers during outbound calls.
•	As a customer, I want to build a precise customer profile so that I can be matched with an RM that suits my needs.
•	As a customer, I want to be able to talk to an interactive voice response so that I can be directed to the appropriate and suitable relationship manager.

(These include all of our user stories that do not overlap).

**Comment by alisalam5** [comment]
Agreed. Sounds good.

**Comment by karinalieu** [comment]
Yep that looks good!

**Comment by Leng-Houston** [comment]
good good
