### ISSUE TITLE
HMW

### ISSUE THREAD

**Issue by Leng-Houston** [alisalam5/ISDM-Team3#22]
How might we address cultural differences between some customers and RMs?

How might we assist customers with specific travel destinations in mind?

How might we reduce the wait time for customers when all RMs are busy?

How might we reduce the possibility of losing potential customers when all RMs are busy?

How might we match individual RMs and their skillsets to suitable customers?

How might we segment or build a better profile of customers?

How might we gather more information about customers to understand their preferences better?

**Comment by alisalam5** [comment]
I will review these and merge it into the problem definition if it is suitable.
