### ISSUE TITLE
Updated Problem Definition

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#24]
Hey guys, I have updated the problem definition by adding a possible problem definition we could use. If you guys think we need to modify it somehow to better suit the project please feel free to discuss with the group. I've also added the _assumptions, stakeholders, POV statements and HMW statements_. Again, please take a look and feel free to **edit** and **add more** of your own. I have only added a title for empathy map as an indicator because we do need to include a diagram for it. Formatted all these updates with bold headings, italics, and listed bullet points or numbers where necessary. If you need more specific info on what I did you can take a look at the pull requests and commits I did. Don't forget to add any issues, PRs, or commits so we can see how we're all progressing thank you!!

**Comment by alisalam5** [comment]
Got you, I will review soon and keep everyone updated

**Comment by Kin-Shun-Jordan-Wong** [comment]
Yep thanks karina, doing great, keep up the good work mate :)
