### ISSUE TITLE
Updated and Finalised User Stories

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#25]
Hey guys I created a new file on the master branch called "UserStories." Jordan and I had to fix and update our user stories as it wasn't that usable to create the use case diagrams. These are uploaded in the file. Any modification or additions to user stories can be done through that. If there are any issues please let us know. 
We also fixed and updated the prioritised product backlog. This can be found in the "diagrams" folder.

**Comment by alisalam5** [comment]
Reviewed and looks great.
