### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#29]
Here's the link to the use case diagrams. Please take a look and let us know if any changes need to made or if there are any issues. Thanks.
https://app.lucidchart.com/invitations/accept/aa5c3c69-f37c-41b2-9cbb-70f0f7b09992

**Comment by Kin-Shun-Jordan-Wong** [comment]
Yep thank you karina lieu, that looks amazing.

**Comment by alisalam5** [comment]
Going to close this issue with the link being provided on the project board this issue is resolved. Thanks guys.
