### ISSUE TITLE
Change use cases

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#30]
Hi guys, ive done a quick change on the diagram for use case diagrams. I notice that one of the actors should not be an "3rd" party, so I changed it to HRM manager because I believe it would most appropriate.

**Comment by karinalieu** [comment]
yes I also believe that is correct.

**Comment by alisalam5** [comment]
Agreed. Will continue to review the diagrams.
