### ISSUE TITLE
New Use Story

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#31]
As an RM, I want to log the call outcome, so that I can keep track of customer details such as the number of calls made or products purchased.

**Comment by Kin-Shun-Jordan-Wong** [comment]
WAOH KARINA I BET UR GOING TO SAY WAOH

**Comment by karinalieu** [comment]
wow yes we are going to need that!! 👍

**Comment by alisalam5** [comment]
Yep that makes alot of sense. This issue can now be closed. Please open a new one for any updates.
