### ISSUE TITLE
HMW, POV, use cases

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#32]
Hi guys, sorry I did not notice that I have not uploaded my HMW, POV, and use cases, but here it is. Please have a look for me if anything is wrong or does anything that overlaps with yours.  Sorry about that. 

POV Statements:
1.	Young consumers need a convenient and smooth way to arrange their holiday travel because planning and organising a trip requires significant research and can be frustrating.
2.	Software developers within this travel company need to produce an efficient system that best matches a consumer with a suitable relationship manager because it will allow them to provide a greater product offering thus leading to increased sales.
3.	Relationship managers within this travel company need to gain valuable insights and specialize in certain travel locations because this will significantly develop their knowledge and skills in providing exceptional services.

How might we statement:
1.	How might we redesign our call management centre for our company so that consumers are matched with better suitable relationship managers.
2.	How might we alter our holiday buying experience for consumers in order to create an efficient and convenient service.
3.	How might we improve our outbound call system for consumers so that relationship managers can gains a greater understanding and provide specialised service based on their needs and wants.

User stories:
As a relationship manager, I want to create supporting tool so that I can match with certain customers that are best suitable to my specialised knowledge and skills.
As a relationship manager, I want the system to generate significant guidelines and a script so that I can provide an improved service to the end-customer.
As a relationship manager, I want the outbound call system to create a target list so that I can have a history of past products proposed and potential customers.
As a customer, I want to be served by the most suitable relationship manager based on my profile and interest so that I can gain a greater understanding of my desired holiday trip.
As a customer, I want to be able to talk to an interactive voice response so that I can be directed to the appropriate and suitable relationship manager.

**Comment by alisalam5** [comment]
I have used this and incorporated suitable elements of your work into our problem definition :)
