### ISSUE TITLE
First iteration of activity diagram

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#35]
Hi guys, so Karina and I just finished rough draft of a part of our case study for the activity diagram. Please have a look and provide any suggestions.

![Activity diagram - Activity Diagram](https://user-images.githubusercontent.com/62321881/83322971-d3ca3b80-a29e-11ea-9196-fd7b28090ad3.png)

**Comment by karinalieu** [comment]
We're going to need to definitely further expand by including the activities about what happens after getting customer profile, such as redirecting the call to RM, getting guidelines and script, logging the call outcome etc. Will continue working on it and add greater detail by end of tonight. Please take a look at the link provided on the project board to our activity diagrams to see our progress.

**Comment by alisalam5** [comment]
This looks solid. I am viewing the diagrams and making comments right now.
