### ISSUE TITLE
Second iteration of activity diagram

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#38]
Hi guys, this is another iteration of our activity diagram that we have updated and fixed based on suggestions and ideas. We have added Interactive Voice Response and Automatic Call Distributor as well as the remaining activities. Please let us know if there are more issues.

![Activity diagram - Activity Diagram](https://user-images.githubusercontent.com/62322349/83323550-f9594400-a2a2-11ea-9843-80fedc4b8b1c.png)

**Comment by karinalieu** [comment]
Hi guys, this is another iteration of our activity diagram that we have updated and fixed based on suggestions and ideas. We have added Interactive Voice Response and Automatic Call Distributor as well as the remaining activities. Please let us know if there are more issues.

**Comment by alisalam5** [comment]
I think the diagram is a bit incomplete. The diagrams seems a bit scattered.

**Comment by karinalieu** [comment]
Noted. Will adjust accordingly by going through the case study and use case diagrams again to ensure all essential steps are included.
