### ISSUE TITLE
outgoing call collab diagram

### ISSUE THREAD

**Issue by Leng-Houston** [alisalam5/ISDM-Team3#39]
Review please. Cheers
![Outgoing](https://user-images.githubusercontent.com/62278180/83323774-51dd1100-a2a4-11ea-80e4-ff435c0809a1.png)

**Comment by Leng-Houston** [comment]
Updated version.
![Outgoing Call](https://user-images.githubusercontent.com/62278180/83351517-1287f080-a388-11ea-8ec8-206bf43e9853.png)

**Comment by alisalam5** [comment]
sounds good! read to upload to the diagrams folder
