### ISSUE TITLE
Final Activity Diagrams

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#48]
Jordan and I have completed what potentially is the final version of our activity diagrams. It has been uploaded into the diagrams folder in the master branch. As seen, it has been split into 3 separate diagrams in order to keep a clear, sequential flow of activities derived from our use case diagrams. Please review and let us know if any further changes are needed.

**Comment by alisalam5** [comment]
Will do ! Will review asap and add any comments here.
