### ISSUE TITLE
The Final Review for the Class Diagram

### ISSUE THREAD

**Issue by alisalam5** [alisalam5/ISDM-Team3#49]
Please review and confirm if everyone is happy with the final version of the Class Diagram. Thanks guys.

**Comment by Kin-Shun-Jordan-Wong** [comment]
Yeah looks really good alisa, thank you for doing that !

**Comment by karinalieu** [comment]
The association between RM Profile class and Questionnaire class can be changed to a normal association. Other than that everything looks good!!
