### ISSUE TITLE
Activity diagram fix

### ISSUE THREAD

**Issue by Kin-Shun-Jordan-Wong** [alisalam5/ISDM-Team3#50]
Hi guys, I think maybe we need to include an activity for voicing call reasons for your activity diagram, any suggestions?

**Comment by karinalieu** [comment]
Yep I agree. We could possibly put a decision point after select options as call reasons only occurs sometimes?

**Comment by Kin-Shun-Jordan-Wong** [comment]
Like this? 
![Activity diagram - AD3](https://user-images.githubusercontent.com/62321881/83346049-a217aa00-a35c-11ea-846a-90eb76b1e175.png)

**Comment by karinalieu** [comment]
Yep!! That looks good :) Upload it to diagrams
